# -*- coding: utf-8 -*-
"""01.Hello, World!

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DaTV6HPl0KJzABZ6mP_xpc-fbt-Jx4Kp
"""

#Hello visitors! Welcome, to this collection of Python codes.
#This particular section/folder is for all the basic/beginner level codes.
#Although they are very simple, these codes are the building blocks.
#We'll be using them in more advanced projects later on.
#Anything written after the Hash(#) symbol is a "Single comment line".
#Comments are NOT executed (or even read) when you run/compile the code.
#Comments are used to describe the code or parts of the code.
#They're for the coder, as well others who might read the code
"""
This is a comment block.
Meaning, you can write an entire paragraph/section of comment here.
This first piece of code we'll be writing is the simplest of them all.
A print statement that prints out, 
"Hello, World!" - two words that mark the start of every programmer's journey
"""
# -> ACTUAL CODE BEGINS HERE <-

print("Hello, World!")

#As you can see, the print statement is very simple.