# -*- coding: utf-8 -*-
"""03_a_conditional_statements.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mV4A3IPSgQCSAZ8zkKCmiJ4MIvay1VkB
"""

#conditional statements are 'if-else' statements
#basically meaning - if this is true, do this, or else, do this

if 5>2:
  print("Yes. 5 is greater than 2.")

#If/Elif statements are followed by a colon (:)
# **NOTE: INDENDTATION is very important in Python

userInput = input("Enter: ") #Enter either a,b,c

if userInput=="a":
  print("A")
elif userInput=="b": #elif means else-if
  print("B")
else:
  print("C")