# -*- coding: utf-8 -*-
"""04_nested_conditional_statements.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-uf6_ZRZKs3tdhf-QruJu0jWX--_L0Ri
"""

#Nested conditionals are basically one if-else condition inside another

a=input("Enter A: ")
b=input("Enter B: ")

a=int(a) #Input is taken as String.
b=int(b) #We type cast them into Integars

if a == 1:
  if b == 2:
    print("Option X")
  else:
    print("Option Y")
elif a == 2:
  if b == 1:
    print("Option U")
  else:
    print("Option V")