# -*- coding: utf-8 -*-
"""05_logical_operators.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SalH1UkWOP9hWaOmunphDHRroMrHjAzq
"""

#In this code, we will fiddle with the logical operators
#AND -> All conditions involved must be true
#OR -> One condition involved must be true
#NOT (!) -> Reverses the result

a = 5
b = 5
c = 4
d = 2

if a == 5 and b == 5: #Both are true
  print("YES")

if a == 5 and b == 7: #Only one is true
  print("YES")
else:
  print("NOPE")

if a == 5 or d == 2: #Only one is true
  print("YES AGAIN")

if a == 1 or d == 2: #Only one is true
  print("YES AGAIN, SIGH")

if a == 0 or d == 0: #Both are false
  print("YES AGAIN, AGAIN")
else:
  print("NOPE! NOT THIS TIME")

if not(a == 0 or d == 0): #Both are false
  print("TADA")