# -*- coding: utf-8 -*-
"""Worked_out_Problem_08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vcdJrwL2aYt06XZ9EH0dA0bxlGkw2JlA
"""

"""
~ PROBLEM 08

Build a simple search tool. 
Search a block of text for a user defined word.
If the word exists, return true, else return false. 

"""

a = "Hello. This is a PYTHON demo script"   #String to check
wordSearch = input('Find the word: ')       #Word to be searched for
aList = list(a.split())                     #Break string into items

#Note: This method is CASE SENSITIVE

print("Case sensitive - ")
if wordSearch in aList:
  print("True")
else:
  print("False")

#NOTE: This method ignores CASE (in a way)

a=a.casefold()                              #casefold() converts into lower case
wordSearch=wordSearch.casefold()
aList = list(a.split()) 

print("NOT case sensitive - ")
if wordSearch in aList:
  print("True")
else:
  print("False")