# -*- coding: utf-8 -*-
"""Worked_out_Problem_05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oQX-TaTykkvDFdl1YO31KVF8v-NNEBJC
"""

"""
~ PROBLEM 05

Print the Fibonacci series, upto the 10th number.

"""
#Initializing the first two values
a = 0
b = 1
temp = 0 #Temporary variable to store the sums

#Print out the first two numbers of the series
print(a)
print(b)

#Initialize the loop
n = 10
i = 2 #Starts from 2, as 0, 1 are already accounted for

#Loop to retrieve rest of the 8 numbers
while i<n:
  temp = a + b
  print(temp)
  a = b
  b = temp
  i = i + 1