# -*- coding: utf-8 -*-
"""Worked_out_Problem_04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kxwuDJhHk9XPmKoXl8ez5L8B5-ebjV3B
"""

"""
~ PROBLEM 04

Take a number. Say whether it is a:
a. Even or Odd number
b. Prime or Non-Prime number

NOTE: Ignore the case of zero 

"""
n = input("Enter Number: ")
n = int(n)

#Check Odd/Even
if n%2==0:
  print(n, "is an Even Number")
else:
  print(n, "is an Odd Number")

#Check Prime/Non-Prime
c = 0
i = 1
while i<=n:
  if n%i==0:
    c = c + 1
  i = i + 1

if c>2:
  print(n, "is a Non-Prime Number") 
else:
  print(n, "is a Prime Number")