# -*- coding: utf-8 -*-
"""Worked_out_Problem_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ziz3jbMLH160yc5wbHpoRql0dQXmjKno
"""

'''
~ PROBLEM 01

Write a program that reads a student’s mark for a single subject, 
and prints out the corresponding grade for that mark. The mark ranges and  
corresponding grades are shown in the table below. 
Valid range of marks is 0 to 100. Print “Wrong Input” otherwise.

NOTE: ERROR HANDLING IS NOT NEEDED.

Marks           Grade
90 and above      A
80-89             B
70-79             C
60-69             D
50-59             E
Below 50          F

'''
m = input("Enter Marks:") #Retrieve marks from the user
m=int(m)                  #Type Casting from String to Int
if m<0 or m>100:
  print("Wront Input")
elif m>=90 and m<=100:
  print("A")
elif m>=80 and m<90:
  print("B")
elif m>=70 and m<80:
  print("C")
elif m>=60 and m<70:
  print("D")
elif m>=50 and m<60:
  print("E")
else:
  print("F")